---
kube-prometheus-stack:
  prometheus:
    ingress:
      enabled: true
      hosts:
        - prometheus.127.0.0.1.nip.io
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.127.0.0.1.nip.io
