---
argo-cd:
  global:
    domain: argocd.127.0.0.1.nip.io
    image:
      imagePullPolicy: Always
    revisionHistoryLimit: 0
  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  configs:
    cm:
      exec.enabled: true
      extension.config: |
        extensions:
          - name: metrics
            backend:
              services:
                - url: argo-cd-metrics-server:9003
    params:
      server.enable.proxy.extension: true
      server.insecure: true
    rbac:
      policy.csv: |-
        p, role:readonly, extensions, invoke, metrics, allow
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    enabled: false
  notifications:
    enabled: false
  redis:
    enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  redisSecretInit:
    enabled: false
  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  server:
    ingress:
      enabled: true
      tls: true
    initContainers:
      - name: extension-metrics
        image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.5
        env:
        - name: EXTENSION_URL
          value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.3/extension.tar.gz
        - name: EXTENSION_CHECKSUM_URL
          value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.3/extension_checksums.txt
        volumeMounts:
          - name: extensions
            mountPath: /tmp/extensions/
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    volumeMounts:
      - name: extensions
        mountPath: /tmp/extensions/
    volumes:
      - name: extensions
        emptyDir: {}