---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: argo-cd-apps
  namespace: argo
spec:
  project: argo-cd-metrics-extension
  source:
    repoURL: https://github.com/christianhuth/minikube.git
    targetRevision: argo-cd-metrics-extension
    path: argo-cd-metrics-extension/04-argo-cd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
