---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-metrics-server
  namespace: argo
spec:
  project: argo-cd-metrics-extension
  source:
    repoURL: https://github.com/christianhuth/minikube.git
    targetRevision: main
    path: argo-cd-metrics-extension/02-argo-cd-metrics-server/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
