---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo
spec:
  project: argo-cd-metrics-extension
  source:
    repoURL: https://github.com/christianhuth/minikube.git
    targetRevision: argo-cd-metrics-extension
    path: argo-cd-metrics-extension/01-kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
