backstage:
  backstage:
    appConfig:
      app:
        baseUrl: http://backstage.127.0.0.1.nip.io
        experimental:
          packages: all
        support:
          url: https://github.com/backstage/backstage/issues # Used by common ErrorPage
          items: # Used by common SupportButton component
            - title: Issues
              icon: github
              links:
                - url: https://github.com/backstage/backstage/issues
                  title: GitHub Issues
            - title: Discord Chatroom
              icon: chat
              links:
                - url: https://discord.gg/backstage-687207715902193673
                  title: '#backstage'
        title: cloud37 Backstage
      auth:
        environment: development
        providers:
          microsoft:
            development:
              clientId: 8ac37114-1c75-4d64-9058-a67c1564c23b
              clientSecret: fkI8Q~zITuaBngpFEvGcjKHZIFEprqSGJ73Gea3k
              tenantId: 66ca1cc0-0f8a-4f99-8148-cba0a17a9ca0
              signIn:
                resolvers:
                  - resolver: emailMatchingUserEntityProfileEmail
                  - resolver: emailLocalPartMatchingUserEntityName
                  - resolver: emailMatchingUserEntityAnnotation
      backend:
        baseUrl: http://backstage.127.0.0.1.nip.io
      kubernetes:
        serviceLocatorMethod:
          type: 'multiTenant'
        clusterLocatorMethods:
          - type: 'config'
            clusters:
              - url: https://kubernetes.default.svc
                name: minikube
                authProvider: 'serviceAccount'
                skipTLSVerify: false
                skipMetricsLookup: true
      organization:
        name: cloud37 Deutschland GmbH
      permission:
        enabled: true
      techdocs:
        builder: 'local'
        generator:
          runIn: 'local'
        publisher:
          type: 'local'
    revisionHistoryLimit: 0
  ingress:
    enabled: true
    host: backstage.127.0.0.1.nip.io
  serviceAccount:
    create: true
