---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-cd-metrics-server
  name: argo-cd-metrics-server
  namespace: argo
spec:
  ports:
    - name: metrics
      port: 9003
      targetPort: 9003
  selector:
    app: argo-cd-metrics-server
