{
 "title": "Linux User and Group Information",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(linux_user_info,instance)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(linux_user_info{instance=~\"$instance\"},username)"
    }
   },
   {
    "name": "groupname",
    "label": "Groupname",
    "query": {
     "query": "label_values(linux_group_info{instance=~\"$instance\"},groupname)"
    }
   },
   {
    "name": "excluded_usernames",
    "label": "Excluded Usernames",
    "query": {
     "query": "label_values(linux_user_info{instance=~\"$instance\"},username)"
    }
   },
   {
    "name": "excluded_groupnames",
    "label": "Excluded Groupnames",
    "query": {
     "query": "label_values(linux_group_info{instance=~\"$instance\"},groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "linux_user_info{instance=~\"$instance\", username=~\"$username\", username!~\"$excluded_usernames\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "linux_group_info{instance=~\"$instance\", groupname=~\"$groupname\", groupname!~\"$excluded_groupnames\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Group Membership",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "linux_group_membership{instance=~\"$instance\", groupname=~\"$groupname\", username=~\"$username\", username!~\"$exclude_usernames\", groupname!~\"$excluded_groupnames\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}